annotations:
  artifacthub.io/changes: "- kind: fixed\n  description: The following security vulnerabilities
    are fixed in Synthetic PoP:CVE-2025-30698,CVE-2025-54798,CVE-2025-56200,CVE-2025-64118,CVE-2025-64718,CVE-2025-64756
    \n"
  artifacthub.io/links: |
    - name: Instana website
      url: https://www.instana.com
    - name: Instana Synthetic PoP Helm charts
      url: https://github.com/instana/synthetic-pop-charts
apiVersion: v2
appVersion: 1.310.0
description: Helm chart to install Instana Synthetic PoP (Point of Presence)
home: https://artifacthub.io/packages/helm/instana/synthetic-pop
icon: https://agents.instana.io/helm/synthetic-pop-logo.png
maintainers:
- email: mccormik@us.ibm.com
  name: Karl McCormick
- email: ediazgallego@ibm.com
  name: Esteban Diaz Gallego
- email: Swetha.Lohith@ibm.com
  name: Swetha Lohith
- email: czhang@us.ibm.com
  name: Carol Zhang
name: synthetic-pop
type: application
version: 1.2.33
