annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: |
        The following security vulnerabilities are fixed in Synthetic PoP:
        - CVE-2026-8723
        - CVE-2026-33750
        - CVE-2026-41907
        - CVE-2026-44705
  artifacthub.io/links: |
    - name: Instana website
      url: https://www.instana.com
    - name: Instana Synthetic PoP Helm charts
      url: https://github.com/instana/synthetic-pop-charts
apiVersion: v2
appVersion: 1.321.0
description: Helm chart to install Instana Synthetic PoP (Point of Presence)
home: https://artifacthub.io/packages/helm/instana/synthetic-pop
icon: https://agents.instana.io/helm/synthetic-pop-logo.png
maintainers:
- email: ediazgallego@ibm.com
  name: Esteban Diaz Gallego
- email: Swetha.Lohith@ibm.com
  name: Swetha Lohith
- email: navaminarendralal@ibm.com
  name: Navami Narendralal
name: synthetic-pop
type: application
version: 1.2.48
