annotations:
  artifacthub.io/changes: "- kind: fixed\n  description: |\n    The following security
    vulnerabilities are fixed in Synthetic PoP:\n    - CVE-2026-18149\n    - CVE-2026-18540\n
    \   - CVE-2026-19534\n    - CVE-2026-84890\n    - CVE-2026-84933\n    - CVE-2026-84947\n
    \   - CVE-2026-84961\n    - CVE-2026-85008\n    - CVE-2026-85014\n    - CVE-2026-85024\n
    \   - CVE-2026-85152\n- kind: changed\n  description: |\n    Upgraded the Synthetic
    PoP BrowserScript playback engine to Chrome 154. See: https://developer.chrome.com/release-notes\n-
    kind: changed\n  description: |\n    Upgraded the Synthetic PoP BrowserScript
    playback engine to Firefox 155. See: https://www.firefox.com/en-US/firefox/155.0/releasenotes\n
    \   \n"
  artifacthub.io/links: |
    - name: Instana website
      url: https://www.instana.com
    - name: Instana Synthetic PoP Helm charts
      url: https://github.com/instana/synthetic-pop-charts
apiVersion: v2
appVersion: 1.327.0
description: Helm chart to install Instana Synthetic PoP (Point of Presence)
home: https://artifacthub.io/packages/helm/instana/synthetic-pop
icon: https://agents.instana.io/helm/synthetic-pop-logo.png
maintainers:
- email: ediazgallego@ibm.com
  name: Esteban Diaz Gallego
- email: Swetha.Lohith@ibm.com
  name: Swetha Lohith
- email: navaminarendralal@ibm.com
  name: Navami Narendralal
name: synthetic-pop
type: application
version: 1.2.58
